[package]
name = "hyst-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "hyst"
path = "src/main.rs"

[dependencies]
hyst-audio = { path = "../hyst-audio" }
hyst-compile = { path = "../hyst-compile" }
hyst-output = { path = "../hyst-output" }
hyst-previz = { path = "../hyst-previz" }
serde.workspace = true
serde_json.workspace = true
