import type { PatchGraph } from '../../../src/render/conductor/patchgraph/types'
import type { FixtureDocument } from '../../../src/render/conductor/patchgraph/fixture-document'

// Plain JSON.stringify rather than hand-formatted source: every field on a
// PatchGraphNode/FixtureInstance is JSON-safe data (no functions, no
// undefined-that-matters), so this is a correct, complete serialization
// with no special-casing per node kind needed — the whole point of
// "routing is data" (SINTEZA_SIGNAL_BUS.md §5.1) is that it doesn't need a
// bespoke printer to round-trip. One unified graph now covers both the
// screen's own targets and any fixture channels (see AGENTS.md's "unify
// screen + physical patch graphs" note) — there's no separate screen-only
// save path anymore; use patchgraph/prune.ts's pruneGraphToTargets on the
// saved graph if you need just the screen-relevant subset back out.
export function serializeGraphAndFixtures(graph: PatchGraph, fixtures: FixtureDocument): string {
  return `// Generated by the patchbay editor (npm run patchbay) -- a saved
// patch graph (screen targets and/or physical fixture channels) + the
// fixture instances its target ids refer to. Fixture instance ids are only
// stable within the session that created them (see fixture-document.ts's
// makeFixtureId) -- re-adding fixtures from the \`fixtures\` array below in
// the same order reproduces the same ids, but this is a snapshot for
// reference/editing, not a live-loadable config on its own.
import type { PatchGraph } from '../../types'
import type { FixtureInstance } from '../../fixture-document'

export const graph: PatchGraph = ${JSON.stringify(graph, null, 2)}

export const fixtures: FixtureInstance[] = ${JSON.stringify(fixtures.fixtures, null, 2)}
`
}

export interface SaveResult {
  ok: boolean
  path?: string
  message?: string
}

export async function saveToFile(filename: string, source: string): Promise<SaveResult> {
  try {
    const res = await fetch('/__patchbay-save', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ filename, source }),
    })
    const text = await res.text()
    if (!res.ok) return { ok: false, message: text }
    const parsed = JSON.parse(text) as { ok: true; path: string }
    return { ok: true, path: parsed.path }
  } catch (err) {
    return { ok: false, message: err instanceof Error ? err.message : String(err) }
  }
}
