// Enttec DMX USB PRO "Widget API" framing — master-prompt.md §5's #4
// priority protocol ("DMX512 via USB-serial, Bridge-mediated"). Real USB-
// DMX dongles almost universally either speak this exact protocol (Enttec's
// own PRO/Mk2) or a close variant of it (many cheap "USB-DMX512" dongles
// clone it, since Enttec published it openly) — a genuinely common target,
// unlike inventing a bespoke framing. Reference:
// https://cdn.sparkfun.com/assets/9/9/1/f/2/DMX_USB_PRO_API_Spec.pdf
//
// Deliberately NOT "Open DMX USB"-style raw framing: that variant needs the
// HOST to generate a real DMX break/mark-after-break at the UART level,
// which the Web Serial API has no facility for at all (no send-break
// method in its spec) — Enttec's framed protocol sidesteps this entirely
// because the *dongle's own firmware* generates the real DMX signal/break;
// the host just sends this framed packet over an ordinary serial
// connection at a fixed baud rate. This is why Enttec-protocol dongles are
// the natural (arguably only practical) Web Serial target.
const START_BYTE = 0x7e
const END_BYTE = 0xe7
const LABEL_OUTPUT_ONLY_SEND_DMX = 6

// Enttec DMX USB PRO's documented default serial parameters for the host
// connection (the DMX-side timing is generated by the dongle itself, not
// by this baud rate).
export const ENTTEC_BAUD_RATE = 250000

// Wraps up to 512 DMX channel values (0..255 each) into a real "Output Only
// Send DMX Packet" (Label 6) frame — the DMX start code (0x00) is prepended
// by this encoder, same convention as sacn.ts's encodeSacnDmx.
export function encodeEnttecDmxPacket(data: Uint8Array): Uint8Array {
  const channels = data.subarray(0, 512)
  const payloadLen = 1 + channels.length // start code + channels
  const buf = new Uint8Array(4 + payloadLen + 1)
  buf[0] = START_BYTE
  buf[1] = LABEL_OUTPUT_ONLY_SEND_DMX
  buf[2] = payloadLen & 0xff // Data Length LSB
  buf[3] = (payloadLen >> 8) & 0xff // Data Length MSB
  buf[4] = 0x00 // DMX start code
  buf.set(channels, 5)
  buf[buf.length - 1] = END_BYTE
  return buf
}
