const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(process.argv[2],'utf8');
const match=source.match(/\/\/ ARM_TIMING_HELPERS_BEGIN([\s\S]*?)\/\/ ARM_TIMING_HELPERS_END/);
assert(match);const context={};vm.createContext(context);
vm.runInContext(match[1]+';this.api={cleanBeats,beatFromGrid,manualBeat,gridBeat,transportBeat};',context);
const {cleanBeats,beatFromGrid,manualBeat,gridBeat,transportBeat}=context.api;
const close=(a,b)=>assert(Math.abs(a-b)<1e-9,`${a} != ${b}`);
const irregular=cleanBeats([1,1.5,2.2]);
close(beatFromGrid(.5,irregular,120),-1);close(beatFromGrid(1.25,irregular,120),.5);
close(beatFromGrid(1.85,irregular,120),1.5);close(beatFromGrid(2.9,irregular,120),3);
close(manualBeat(1.5,110,.5),110/60);close(gridBeat(2,'manual',[],110,.5,.5),110/60);
for(const bad of [[],[1],[0,10,3,4],[0,1,1],[0,-1,2],[0,NaN,2],[0,Infinity,2],[0,'1',2],null])assert.equal(cleanBeats(bad).length,0);
close(gridBeat(2,'detected',cleanBeats([0,10,3,4]),120,0,0),4);
close(transportBeat(true,12.25,999,'manual',[],120,.25,0),transportBeat(true,12.25,-999,'manual',[],120,.25,0));
close(transportBeat(true,5,77,'manual',[],120,1,0),8);close(transportBeat(true,9,77,'manual',[],120,1,0),16);
const scoreMatch=source.match(/(function validSong[\s\S]*?)\n  window\.__ARM_SCORE__/);
assert(scoreMatch);const scoreContext={};vm.createContext(scoreContext);
vm.runInContext(scoreMatch[1]+';this.api={validSong,sampleSong,cueAt,shiftedScoreSeconds,visualAt};',scoreContext);
const {validSong,sampleSong,cueAt,shiftedScoreSeconds,visualAt}=scoreContext.api;
const score=validSong({duration:2,fps:2,frames:[[0,0,0,0,0,0,0,0,0,'rest'],[2,0,2,0,2,0,20,0,0,'reach'],[4,0,4,0,4,0,40,0,0,'hold'],[6,0,6,0,6,0,60,0,0,'end']],cues:[{start:.5,end:1,gesture:'reach'},{start:1,end:2,gesture:'hold'}]});
assert(score);close(sampleSong(score,-99)[0],0);close(sampleSong(score,.25)[0],1);close(sampleSong(score,99)[0],6);
assert.equal(cueAt(score,.5).gesture,'reach');assert.equal(cueAt(score,1).gesture,'hold');assert.equal(cueAt(score,2).gesture,'hold');assert.equal(cueAt(score,2.001),null);
const short=validSong({duration:1.01,fps:60,frames:Array.from({length:62},(_,i)=>[i,0,i,0,i,0,i,0,0,'end']),cues:[]});
close(sampleSong(short,1.005)[0],60.5);close(sampleSong(short,1.01)[0],61);
close(shiftedScoreSeconds(10,2,12),8);close(shiftedScoreSeconds(1,2,12),0);close(shiftedScoreSeconds(99,0,12),12);
assert.equal(validSong({duration:2,frames:[[0,0]]}),null);
console.log('arm timing helpers: passed');

const visualScore={duration:4,cues:[{start:0,end:2,energy:.4,accent:.8,arrivalAnchor:1},{start:2,end:4,energy:0,accent:0}]};
close(visualAt(visualScore,1).accent,.8);close(visualAt(visualScore,3).accent,0);
assert(visualAt(visualScore,0).accent<.0001);
assert(Math.abs(visualAt(visualScore,2-1e-6).energy-visualAt(visualScore,2+1e-6).energy)<1e-6);
close(visualAt(visualScore,3).energy,0);
